#ifndef CHROME_BROWSER_EXTENSIONS_API_UTILITIES_CONSTANTS_H_
#define CHROME_BROWSER_EXTENSIONS_API_UTILITIES_CONSTANTS_H_

namespace events {
extern const char kOnClipboardContentChanged[];
}

#endif  // CHROME_BROWSER_EXTENSIONS_API_UTILITIES_CONSTANTS_H_
